### ISSUE TITLE
Creating range of ZonedDateTime, 2 inconsistencies with DateTime version

### ISSUE THREAD

**Issue by JockLawrie** [JuliaTime/TimeZones.jl#104]
Hi there,

I am creating a range of `ZonedDateTime`, using `Julia 0.6.1`.

Using only `Base.DateTime` I do the following, and all is well:
```julia
using Base.Dates
dttm1 = DateTime("2017-10-01 09:00", "Y-m-d H:M")
dttm2 = DateTime("2017-12-08 23:00", "Y-m-d H:M")
r = dttm1:dttm2
```

Using `ZonedDateTime` I do the following:
```julia
using Base.Dates
using TimeZones
tz    = TimeZone("Australia/Melbourne")
dttm1 = ZonedDateTime(DateTime("2017-10-01 09:00", "Y-m-d H:M"), tz)
dttm2 = ZonedDateTime(DateTime("2017-12-08 23:00", "Y-m-d H:M"), tz)
r = dttm1:dttm2
```
Although both versions work, I see 2 issues:
1. The `DateTime` version has stepsize of 1 day, whereas the `ZonedDateTime` version has stepsize 1 millisecond.
2. The `ZonedDateTime` version gives the following deprecation warning:
```julia
WARNING: convert(::Type{T}, x::Real) where T <: Dates.Period is deprecated, use T(x) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] convert(::Type{Base.Dates.Millisecond}, ::Int64) at ./deprecated.jl:57
 [3] colon(::TimeZones.ZonedDateTime, ::TimeZones.ZonedDateTime) at ./range.jl:9
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [6] macro expansion at ./REPL.jl:97 [inlined]
 [7] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
```

Are these 2 issues real and to be fixed?
Or is my understanding flawed and I should be doing something different?

Thanks,
Jock

**Comment by omus** [comment]
Thanks for filing this issue Jock. 

> 1. The `DateTime` version has stepsize of 1 day, whereas the `ZonedDateTime` version has stepsize 1 millisecond.

I think having the step size default to be 1 day is much more reasonable than the current 1 millisecond. I'll note however that in Julia 0.7 that specifying a `DateTime` range without a step is deprecated:

```julia
julia> DateTime(2000,1):DateTime(2000,2)
WARNING: colon(start::T, stop::T) where T <: DateTime is deprecated, use start:Day(1):stop instead.
```
I'll address this for Julia 0.6 however.

> 2. The `ZonedDateTime` version gives the following deprecation warning:

That warning is mostly due to me not setting a default step in Julia 0.6. Essentially the issue is that `oftype` calls `convert(::Type{<:Period}, ::Real)` which has been deprecated in favor of using `T(x)`. Details about this can be found in [this issue](https://github.com/JuliaLang/julia/issues/16116).

Don't worry about the deprecation warning as I'll address this with the fix to 1. Thanks again for the report.

**Comment by JockLawrie** [comment]
Thanks for replying.
No need to change. If the absence of a step size is deprecated for Julia 0.7 we may as well get used to it now.

Thanks again,
Jock

**Comment by omus** [comment]
I would definitely advise that you specify a step size. That said I'll still be changing the default for 0.6 to avoid confusion with the warning you saw and it'll allow me to introduce a deprecation in 0.7.
